# Generated by Django 3.2.6 on 2021-12-05 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('hostname', models.URLField(max_length=255, verbose_name='Hostname')),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=255, verbose_name='Протокол')),
                ('homepage_url', models.URLField(max_length=255, verbose_name='URL главной страницы')),
                ('is_available', models.BooleanField(verbose_name='Доступность сайта')),
                ('has_sitemap_xml', models.BooleanField(verbose_name='Есть карта сайта (XML)')),
                ('created_date', models.DateField(null=True, verbose_name='Дата создания сайта')),
                ('last_modified', models.CharField(max_length=255, null=True, verbose_name='Последнее обновление')),
                ('domain_expiration_date', models.DateField(null=True, verbose_name='Срок домена')),
                ('loading_speed', models.IntegerField(default=0, verbose_name='Скорость загрузки сайта')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес сайта')),
                ('tls_version', models.CharField(max_length=255, null=True, verbose_name='SSL/TLS version')),
                ('os_version', models.CharField(max_length=255, null=True, verbose_name='Версия ОС')),
                ('os_warning', models.CharField(max_length=5000, null=True, verbose_name='Предупреждения ОС')),
                ('php_version', models.CharField(max_length=255, null=True, verbose_name='Версия PHP')),
                ('php_warning', models.CharField(max_length=5000, null=True, verbose_name='Предупреждения PHP')),
                ('web_server_version', models.CharField(max_length=255, null=True, verbose_name='Версия web сервера')),
                ('web_server_warning', models.CharField(max_length=5000, null=True, verbose_name='Предупреждения web сервера')),
                ('framework_name', models.CharField(max_length=255, null=True, verbose_name='Фреймворк/CMS')),
                ('framework_warning', models.CharField(max_length=5000, null=True, verbose_name='Предупреждения фреймворка')),
                ('total_links_count', models.IntegerField(default=0, verbose_name='Кол-во ссылок')),
                ('broken_links_count', models.IntegerField(default=0, verbose_name='Кол-во битых ссылок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sites', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
                'db_table': 'sites',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteVulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('text', models.CharField(max_length=5000, null=True, verbose_name='Текст уязвимости')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sitevulnerabilitiess', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='main.site', verbose_name='Сайт')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sitevulnerabilitiess', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Уязвимость',
                'verbose_name_plural': 'Уязвимости',
                'db_table': 'site_vulnerabilities',
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteOpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('port', models.IntegerField(verbose_name='Номер порта')),
                ('is_critical', models.BooleanField(verbose_name='Критично?')),
                ('warning_msg', models.CharField(max_length=1000, verbose_name='Текст предупреждения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_siteopenports', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_ports', to='main.site', verbose_name='Сайт')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_siteopenports', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Открытый порт',
                'verbose_name_plural': 'Открытые порты',
                'db_table': 'site_open_ports',
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteBrokenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('http_code', models.IntegerField(default=404, verbose_name='HTTP код')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sitebrokenlinks', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_links', to='main.site', verbose_name='Сайт')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sitebrokenlinks', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'Битая ссылка',
                'verbose_name_plural': 'Битые ссылки',
                'db_table': 'site_broken_links',
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='SiteABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обновления')),
                ('results_text', models.CharField(max_length=5000, verbose_name='Результат ab теста (текст)')),
                ('concurrency_level', models.IntegerField(null=True, verbose_name='Конкурентные потоки')),
                ('complete_requests', models.IntegerField(null=True, verbose_name='Кол-во направленные запросов')),
                ('time_taken', models.FloatField(null=True, verbose_name='Общее время выполнения')),
                ('failed_requests', models.IntegerField(null=True, verbose_name='Провальные запросы')),
                ('total_transferred', models.IntegerField(null=True, verbose_name='Загружено байтов')),
                ('html_transferred', models.IntegerField(null=True, verbose_name='Загружено байтов HTML')),
                ('requests_per_second', models.FloatField(null=True, verbose_name='Среднее кол-во запросов в секунду')),
                ('time_per_request', models.FloatField(null=True, verbose_name='Среднее время выполнения запроса [ms]')),
                ('time_per_request_2', models.FloatField(null=True, verbose_name='Среднее время выполнения запроса по всем потокам [ms]')),
                ('transfer_rate', models.FloatField(null=True, verbose_name='Скорость загрузки [килобайт/сек]')),
                ('connection_time_min', models.FloatField(null=True, verbose_name='Время коннекта (мин.) [ms]')),
                ('connection_time_max', models.FloatField(null=True, verbose_name='Время коннекта (макс.) [ms]')),
                ('connection_time_avg', models.FloatField(null=True, verbose_name='Время коннекта (сред.) [ms]')),
                ('processing_time_min', models.FloatField(null=True, verbose_name='Время обработки (мин.) [ms]')),
                ('processing_time_max', models.FloatField(null=True, verbose_name='Время обработки (макс.) [ms]')),
                ('processing_time_avg', models.FloatField(null=True, verbose_name='Время обработки (сред.) [ms]')),
                ('waiting_time_min', models.FloatField(null=True, verbose_name='Время ожидания (мин.) [ms]')),
                ('waiting_time_max', models.FloatField(null=True, verbose_name='Время ожидания (макс.) [ms]')),
                ('waiting_time_avg', models.FloatField(null=True, verbose_name='Время ожидания (сред.) [ms]')),
                ('total_time_min', models.FloatField(null=True, verbose_name='Время ожидания (мин.) [ms]')),
                ('total_time_max', models.FloatField(null=True, verbose_name='Время ожидания (макс.) [ms]')),
                ('total_time_avg', models.FloatField(null=True, verbose_name='Время ожидания (сред.) [ms]')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_siteabtests', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользоветем')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='main.site', verbose_name='Сайт')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_siteabtests', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено пользоветем')),
            ],
            options={
                'verbose_name': 'AB тест',
                'verbose_name_plural': 'AB тесты',
                'db_table': 'site_ab_tests',
                'ordering': ['site_id'],
            },
        ),
    ]
